language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
before_install:
  - pip install poetry
  - poetry --version
install:
  - poetry install
  - poetry run pip install pytest-cov
  - poetry run pip install coveralls
# command to run tests
script:
  - poetry run pytest tests --cov=okama/
after_success:
  - poetry run coveralls
